services:
  csharp-webapplication1:
    build:
      context: .
      dockerfile: ./WebApplication1/Dockerfile  # Uses the Dockerfile at the project root
    container_name: csharp-webapplication1
    ports:
      - "8080:8080"  # Exposes the app on http://localhost:8080
    volumes:
      - ./Data:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
    init: true
    